# -*- coding: utf-8 -*-
"""Cyber_security_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15PT7r9973f90JgWn7DHnRPdp2-a0e3Te
"""

print("Hello... Harshit This side...")

import requests

from datetime import datetime

api_key = 'f9f0f00517f927a9b7646d0d6c06d5c1'
location = input("Enter the city name: ")

complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q=" + location + "&appid=" + api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

#create variables to store and display data...
temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

A = "_____________________________________________________"
B = "Weather Stats for - {} || {}".format(location.upper(),date_time)
C = "_____________________________________________________"
D = "Current temperature is : {:.2f} deg C".format(temp_city)
E = "Current weather desc :", weather_desc
F = "Current Humidity :", hmdt, '%'
G = "Current wind speed :", wind_spd , 'kmph'

print(A)
print(B)
print(C)

print(D)
print(E)
print(F)
print(G)

with open('storage.txt','w') as f:
  f.write(A)
  f.write("\n")
  f.write(B)
  f.write("\n")
  f.write(C)
  f.write("\n")
  f.write(D)
  f.write('\n')
  f.write("Current weather desc :")
  f.write(weather_desc)
  f.write("\n")
  f.write("Current Humidity :")
  f.write(str(hmdt))
  f.write('%')
  f.write("\n")
  f.write("Current wind speed :")
  f.write(str(wind_spd))
  f.write('kmph')
  f.write("\n")

f.close()